import 'memory_recall_service.dart';

/// Ports server.js's extractTopics/STOPWORDS. Node also filtered out its own generated block
/// ids (base36 timestamp+random strings) leaking into topic lists -- not needed here, since
/// Serverpod rows use plain integer ids that can't collide with extracted English words.
class TopicService {
  static final _stopwords = <String>{
    'the', 'a', 'an', 'is', 'are', 'was', 'were', 'to', 'of', 'and', 'in', 'on', 'for', 'it',
    'i', 'you', 'me', 'my', 'your', 'that', 'this', 'with', 'be', 'do', 'does', 'did', 'so',
    'but', 'if', 'or', 'at', 'as', 'not', 'no', 'yes',
    // self-questioning / reasoning boilerplate -- real content words, but generated by the bot
    // about itself, not signal from the world.
    'drawing', 'blocks', 'block', 'seems', 'connect', 'connects', 'prior', 'thread', 'threads',
    'enough', 'grounding', 'ground', 'grounded', 'treat', 'working', 'answer', 'rather', 'than',
    'guess', 'reconsidering', 'comparing', 'juxtaposing', 'emerges', 'inference', 'logical',
    'weight', 'future', 'replies', 'reply', 'filing', 'memory', 'reasoning', 'log',
    // words from WYRD's canned self-answers ("ties back to a few things I've seen before -- feels
    // like a real thread", "got at least a little to go on"); they topped its concept map
    'ties', 'feels', 'seen', 'least', 'little', 'got', 'something', 'things', 'keeping', 'comes',
    // contractions carry no real content on their own.
    "what's", "who's", "how's", "where's", "when's", "that's", "it's", "there's", "he's",
    "she's", "i've", "you've", "we've", "they've", "i'm", "you're", "we're", "they're",
    "don't", "doesn't", "didn't", "isn't", "aren't", "wasn't", "weren't", "can't", "won't",
    "wouldn't", "couldn't", "shouldn't",
  };

  /// Words too common to be a real subject (shared with the concept map's filter).
  static Set<String> get stopwords => _stopwords;

  /// Words that are never an idea worth showing or wiring (the concept map and the neural
  /// network both skip them): stopwords, question scaffolding and common filler.
  static final Set<String> noise = {
    ..._stopwords, ...MemoryRecallService.scaffold,
    'from', 'like', 'later', 'years', 'other', 'help', 'work', 'just', 'more', 'also', 'into', 'than', 'then',
    'them', 'they', 'this', 'that', 'what', 'with', 'your', 'about', 'which', 'there', 'their', 'would', 'could',
    'should', 'being', 'been', 'have', 'here', 'when', 'where', 'while', 'will', 'were', 'some', 'many', 'much',
    'most', 'very', 'over', 'only', 'even', 'each', 'make', 'made', 'first', 'new', 'one', 'two', 'use', 'used',
    'using', 'way', 'get', 'gets', 'still', 'show', 'says', 'said', 'these', 'those', 'does', 'did', 'doing',
    'after', 'before', 'because', 'through', 'between', 'among', 'during', 'without', 'within', 'part', 'known',
    'per', 'our', 'its', 'might', 'every', 'same', 'may', 'can', 'any', 'all', 'own', 'via', 'etc', 'yet', 'ever',
    'less', 'far', 'lot', 'lots', 'got', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'you',
  };

  /// True for a topic that can be a real idea: not filler, not a number, long enough.
  static bool isIdea(String w) => w.length > 2 && !noise.contains(w) && !RegExp(r'^[0-9]+$').hasMatch(w);

  static final _wordPattern = RegExp(r"[a-z0-9']+");

  static List<String> extractTopics(String text) {
    final matches = _wordPattern.allMatches(text.toLowerCase()).map((m) => m.group(0)!);
    final words = matches.where((w) => w.length > 2 && w.length < 20 && !_stopwords.contains(w));
    return words.toSet().toList();
  }

  static double jaccardSimilarity(List<String> a, List<String> b) {
    if (a.isEmpty && b.isEmpty) return 0;
    final setA = a.toSet();
    final setB = b.toSet();
    final intersection = setA.intersection(setB).length;
    final union = setA.union(setB).length;
    return union > 0 ? intersection / union : 0;
  }
}
