/// Ports server.js's extractTopics/STOPWORDS. Node also filtered out its own generated block
/// ids (base36 timestamp+random strings) leaking into topic lists -- not needed here, since
/// Serverpod rows use plain integer ids that can't collide with extracted English words.
class TopicService {
  static final _stopwords = <String>{
    'the', 'a', 'an', 'is', 'are', 'was', 'were', 'to', 'of', 'and', 'in', 'on', 'for', 'it',
    'i', 'you', 'me', 'my', 'your', 'that', 'this', 'with', 'be', 'do', 'does', 'did', 'so',
    'but', 'if', 'or', 'at', 'as', 'not', 'no', 'yes',
    // self-questioning / reasoning boilerplate -- real content words, but generated by the bot
    // about itself, not signal from the world.
    'drawing', 'blocks', 'block', 'seems', 'connect', 'connects', 'prior', 'thread', 'threads',
    'enough', 'grounding', 'ground', 'grounded', 'treat', 'working', 'answer', 'rather', 'than',
    'guess', 'reconsidering', 'comparing', 'juxtaposing', 'emerges', 'inference', 'logical',
    'weight', 'future', 'replies', 'reply', 'filing', 'memory', 'reasoning', 'log',
    // contractions carry no real content on their own.
    "what's", "who's", "how's", "where's", "when's", "that's", "it's", "there's", "he's",
    "she's", "i've", "you've", "we've", "they've", "i'm", "you're", "we're", "they're",
    "don't", "doesn't", "didn't", "isn't", "aren't", "wasn't", "weren't", "can't", "won't",
    "wouldn't", "couldn't", "shouldn't",
  };

  static final _wordPattern = RegExp(r"[a-z0-9']+");

  static List<String> extractTopics(String text) {
    final matches = _wordPattern.allMatches(text.toLowerCase()).map((m) => m.group(0)!);
    final words = matches.where((w) => w.length > 2 && w.length < 20 && !_stopwords.contains(w));
    return words.toSet().toList();
  }

  static double jaccardSimilarity(List<String> a, List<String> b) {
    if (a.isEmpty && b.isEmpty) return 0;
    final setA = a.toSet();
    final setB = b.toSet();
    final intersection = setA.intersection(setB).length;
    final union = setA.union(setB).length;
    return union > 0 ? intersection / union : 0;
  }
}
