// GENERATED from the `world-countries` npm package (the same data server.js bundled).
// Regenerate rather than hand-editing. Static reference data: no API key, no network call.

class WorldCountryData {
  const WorldCountryData({
    required this.name,
    required this.cca2,
    required this.cca3,
    required this.region,
    required this.subregion,
    required this.lat,
    required this.lng,
    required this.capital,
    required this.languages,
    required this.currencies,
    required this.flag,
  });

  final String name;
  final String cca2;
  final String cca3;
  final String region;
  final String subregion;
  final double lat;
  final double lng;
  final String? capital;
  final List<String> languages;
  final List<String> currencies;
  final String? flag;
}

/// Every country with coordinates, sorted by common name.
const worldCountries = <WorldCountryData>[
  WorldCountryData(
    name: 'Afghanistan',
    cca2: 'AF',
    cca3: 'AFG',
    region: 'Asia',
    subregion: 'Southern Asia',
    lat: 33.000000,
    lng: 65.000000,
    capital: 'Kabul',
    languages: ['Dari', 'Pashto', 'Turkmen'],
    currencies: ['Afghan afghani (؋)'],
    flag: '🇦🇫',
  ),
  WorldCountryData(
    name: 'Åland Islands',
    cca2: 'AX',
    cca3: 'ALA',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 60.116667,
    lng: 19.900000,
    capital: 'Mariehamn',
    languages: ['Swedish'],
    currencies: ['Euro (€)'],
    flag: '🇦🇽',
  ),
  WorldCountryData(
    name: 'Albania',
    cca2: 'AL',
    cca3: 'ALB',
    region: 'Europe',
    subregion: 'Southeast Europe',
    lat: 41.000000,
    lng: 20.000000,
    capital: 'Tirana',
    languages: ['Albanian'],
    currencies: ['Albanian lek (L)'],
    flag: '🇦🇱',
  ),
  WorldCountryData(
    name: 'Algeria',
    cca2: 'DZ',
    cca3: 'DZA',
    region: 'Africa',
    subregion: 'Northern Africa',
    lat: 28.000000,
    lng: 3.000000,
    capital: 'Algiers',
    languages: ['Arabic'],
    currencies: ['Algerian dinar (د.ج)'],
    flag: '🇩🇿',
  ),
  WorldCountryData(
    name: 'American Samoa',
    cca2: 'AS',
    cca3: 'ASM',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -14.333333,
    lng: -170.000000,
    capital: 'Pago Pago',
    languages: ['English', 'Samoan'],
    currencies: ['United States dollar (\$)'],
    flag: '🇦🇸',
  ),
  WorldCountryData(
    name: 'Andorra',
    cca2: 'AD',
    cca3: 'AND',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 42.500000,
    lng: 1.500000,
    capital: 'Andorra la Vella',
    languages: ['Catalan'],
    currencies: ['Euro (€)'],
    flag: '🇦🇩',
  ),
  WorldCountryData(
    name: 'Angola',
    cca2: 'AO',
    cca3: 'AGO',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: -12.500000,
    lng: 18.500000,
    capital: 'Luanda',
    languages: ['Portuguese'],
    currencies: ['Angolan kwanza (Kz)'],
    flag: '🇦🇴',
  ),
  WorldCountryData(
    name: 'Anguilla',
    cca2: 'AI',
    cca3: 'AIA',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.250000,
    lng: -63.166667,
    capital: 'The Valley',
    languages: ['English'],
    currencies: ['Eastern Caribbean dollar (\$)'],
    flag: '🇦🇮',
  ),
  WorldCountryData(
    name: 'Antarctica',
    cca2: 'AQ',
    cca3: 'ATA',
    region: 'Antarctic',
    subregion: '',
    lat: -90.000000,
    lng: 0.000000,
    capital: null,
    languages: [],
    currencies: [],
    flag: '🇦🇶',
  ),
  WorldCountryData(
    name: 'Antigua and Barbuda',
    cca2: 'AG',
    cca3: 'ATG',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 17.050000,
    lng: -61.800000,
    capital: 'Saint John\'s',
    languages: ['English'],
    currencies: ['Eastern Caribbean dollar (\$)'],
    flag: '🇦🇬',
  ),
  WorldCountryData(
    name: 'Argentina',
    cca2: 'AR',
    cca3: 'ARG',
    region: 'Americas',
    subregion: 'South America',
    lat: -34.000000,
    lng: -64.000000,
    capital: 'Buenos Aires',
    languages: ['Guaraní', 'Spanish'],
    currencies: ['Argentine peso (\$)'],
    flag: '🇦🇷',
  ),
  WorldCountryData(
    name: 'Armenia',
    cca2: 'AM',
    cca3: 'ARM',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 40.000000,
    lng: 45.000000,
    capital: 'Yerevan',
    languages: ['Armenian'],
    currencies: ['Armenian dram (֏)'],
    flag: '🇦🇲',
  ),
  WorldCountryData(
    name: 'Aruba',
    cca2: 'AW',
    cca3: 'ABW',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 12.500000,
    lng: -69.966667,
    capital: 'Oranjestad',
    languages: ['Dutch', 'Papiamento'],
    currencies: ['Aruban florin (ƒ)'],
    flag: '🇦🇼',
  ),
  WorldCountryData(
    name: 'Australia',
    cca2: 'AU',
    cca3: 'AUS',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    lat: -27.000000,
    lng: 133.000000,
    capital: 'Canberra',
    languages: ['English'],
    currencies: ['Australian dollar (\$)'],
    flag: '🇦🇺',
  ),
  WorldCountryData(
    name: 'Austria',
    cca2: 'AT',
    cca3: 'AUT',
    region: 'Europe',
    subregion: 'Central Europe',
    lat: 47.333333,
    lng: 13.333333,
    capital: 'Vienna',
    languages: ['Austro-Bavarian German'],
    currencies: ['Euro (€)'],
    flag: '🇦🇹',
  ),
  WorldCountryData(
    name: 'Azerbaijan',
    cca2: 'AZ',
    cca3: 'AZE',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 40.500000,
    lng: 47.500000,
    capital: 'Baku',
    languages: ['Azerbaijani', 'Russian'],
    currencies: ['Azerbaijani manat (₼)'],
    flag: '🇦🇿',
  ),
  WorldCountryData(
    name: 'Bahamas',
    cca2: 'BS',
    cca3: 'BHS',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 24.250000,
    lng: -76.000000,
    capital: 'Nassau',
    languages: ['English'],
    currencies: ['Bahamian dollar (\$)', 'United States dollar (\$)'],
    flag: '🇧🇸',
  ),
  WorldCountryData(
    name: 'Bahrain',
    cca2: 'BH',
    cca3: 'BHR',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 26.000000,
    lng: 50.550000,
    capital: 'Manama',
    languages: ['Arabic'],
    currencies: ['Bahraini dinar (.د.ب)'],
    flag: '🇧🇭',
  ),
  WorldCountryData(
    name: 'Bangladesh',
    cca2: 'BD',
    cca3: 'BGD',
    region: 'Asia',
    subregion: 'Southern Asia',
    lat: 24.000000,
    lng: 90.000000,
    capital: 'Dhaka',
    languages: ['Bengali'],
    currencies: ['Bangladeshi taka (৳)'],
    flag: '🇧🇩',
  ),
  WorldCountryData(
    name: 'Barbados',
    cca2: 'BB',
    cca3: 'BRB',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 13.166667,
    lng: -59.533333,
    capital: 'Bridgetown',
    languages: ['English'],
    currencies: ['Barbadian dollar (\$)'],
    flag: '🇧🇧',
  ),
  WorldCountryData(
    name: 'Belarus',
    cca2: 'BY',
    cca3: 'BLR',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 53.000000,
    lng: 28.000000,
    capital: 'Minsk',
    languages: ['Belarusian', 'Russian'],
    currencies: ['Belarusian ruble (Br)'],
    flag: '🇧🇾',
  ),
  WorldCountryData(
    name: 'Belgium',
    cca2: 'BE',
    cca3: 'BEL',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 50.833333,
    lng: 4.000000,
    capital: 'Brussels',
    languages: ['German', 'French', 'Dutch'],
    currencies: ['Euro (€)'],
    flag: '🇧🇪',
  ),
  WorldCountryData(
    name: 'Belize',
    cca2: 'BZ',
    cca3: 'BLZ',
    region: 'Americas',
    subregion: 'Central America',
    lat: 17.250000,
    lng: -88.750000,
    capital: 'Belmopan',
    languages: ['Belizean Creole', 'English', 'Spanish'],
    currencies: ['Belize dollar (\$)'],
    flag: '🇧🇿',
  ),
  WorldCountryData(
    name: 'Benin',
    cca2: 'BJ',
    cca3: 'BEN',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 9.500000,
    lng: 2.250000,
    capital: 'Porto-Novo',
    languages: ['French'],
    currencies: ['West African CFA franc (Fr)'],
    flag: '🇧🇯',
  ),
  WorldCountryData(
    name: 'Bermuda',
    cca2: 'BM',
    cca3: 'BMU',
    region: 'Americas',
    subregion: 'North America',
    lat: 32.333333,
    lng: -64.750000,
    capital: 'Hamilton',
    languages: ['English'],
    currencies: ['Bermudian dollar (\$)'],
    flag: '🇧🇲',
  ),
  WorldCountryData(
    name: 'Bhutan',
    cca2: 'BT',
    cca3: 'BTN',
    region: 'Asia',
    subregion: 'Southern Asia',
    lat: 27.500000,
    lng: 90.500000,
    capital: 'Thimphu',
    languages: ['Dzongkha'],
    currencies: ['Bhutanese ngultrum (Nu.)', 'Indian rupee (₹)'],
    flag: '🇧🇹',
  ),
  WorldCountryData(
    name: 'Bolivia',
    cca2: 'BO',
    cca3: 'BOL',
    region: 'Americas',
    subregion: 'South America',
    lat: -17.000000,
    lng: -65.000000,
    capital: 'Sucre',
    languages: ['Aymara', 'Guaraní', 'Quechua', 'Spanish'],
    currencies: ['Bolivian boliviano (Bs.)'],
    flag: '🇧🇴',
  ),
  WorldCountryData(
    name: 'Bosnia and Herzegovina',
    cca2: 'BA',
    cca3: 'BIH',
    region: 'Europe',
    subregion: 'Southeast Europe',
    lat: 44.000000,
    lng: 18.000000,
    capital: 'Sarajevo',
    languages: ['Bosnian', 'Croatian', 'Serbian'],
    currencies: ['Bosnia and Herzegovina convertible mark (KM)'],
    flag: '🇧🇦',
  ),
  WorldCountryData(
    name: 'Botswana',
    cca2: 'BW',
    cca3: 'BWA',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -22.000000,
    lng: 24.000000,
    capital: 'Gaborone',
    languages: ['English', 'Tswana'],
    currencies: ['Botswana pula (P)'],
    flag: '🇧🇼',
  ),
  WorldCountryData(
    name: 'Bouvet Island',
    cca2: 'BV',
    cca3: 'BVT',
    region: 'Antarctic',
    subregion: '',
    lat: -54.433333,
    lng: 3.400000,
    capital: null,
    languages: ['Norwegian'],
    currencies: [],
    flag: '🇧🇻',
  ),
  WorldCountryData(
    name: 'Brazil',
    cca2: 'BR',
    cca3: 'BRA',
    region: 'Americas',
    subregion: 'South America',
    lat: -10.000000,
    lng: -55.000000,
    capital: 'Brasília',
    languages: ['Portuguese'],
    currencies: ['Brazilian real (R\$)'],
    flag: '🇧🇷',
  ),
  WorldCountryData(
    name: 'British Indian Ocean Territory',
    cca2: 'IO',
    cca3: 'IOT',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -6.000000,
    lng: 71.500000,
    capital: 'Diego Garcia',
    languages: ['English'],
    currencies: ['United States dollar (\$)'],
    flag: '🇮🇴',
  ),
  WorldCountryData(
    name: 'British Virgin Islands',
    cca2: 'VG',
    cca3: 'VGB',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.431383,
    lng: -64.623050,
    capital: 'Road Town',
    languages: ['English'],
    currencies: ['United States dollar (\$)'],
    flag: '🇻🇬',
  ),
  WorldCountryData(
    name: 'Brunei',
    cca2: 'BN',
    cca3: 'BRN',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: 4.500000,
    lng: 114.666667,
    capital: 'Bandar Seri Begawan',
    languages: ['Malay'],
    currencies: ['Brunei dollar (\$)', 'Singapore dollar (\$)'],
    flag: '🇧🇳',
  ),
  WorldCountryData(
    name: 'Bulgaria',
    cca2: 'BG',
    cca3: 'BGR',
    region: 'Europe',
    subregion: 'Southeast Europe',
    lat: 43.000000,
    lng: 25.000000,
    capital: 'Sofia',
    languages: ['Bulgarian'],
    currencies: ['Bulgarian lev (лв)'],
    flag: '🇧🇬',
  ),
  WorldCountryData(
    name: 'Burkina Faso',
    cca2: 'BF',
    cca3: 'BFA',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 13.000000,
    lng: -2.000000,
    capital: 'Ouagadougou',
    languages: ['French'],
    currencies: ['West African CFA franc (Fr)'],
    flag: '🇧🇫',
  ),
  WorldCountryData(
    name: 'Burundi',
    cca2: 'BI',
    cca3: 'BDI',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -3.500000,
    lng: 30.000000,
    capital: 'Gitega',
    languages: ['French', 'Kirundi'],
    currencies: ['Burundian franc (Fr)'],
    flag: '🇧🇮',
  ),
  WorldCountryData(
    name: 'Cambodia',
    cca2: 'KH',
    cca3: 'KHM',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: 13.000000,
    lng: 105.000000,
    capital: 'Phnom Penh',
    languages: ['Khmer'],
    currencies: ['Cambodian riel (៛)', 'United States dollar (\$)'],
    flag: '🇰🇭',
  ),
  WorldCountryData(
    name: 'Cameroon',
    cca2: 'CM',
    cca3: 'CMR',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: 6.000000,
    lng: 12.000000,
    capital: 'Yaoundé',
    languages: ['English', 'French'],
    currencies: ['Central African CFA franc (Fr)'],
    flag: '🇨🇲',
  ),
  WorldCountryData(
    name: 'Canada',
    cca2: 'CA',
    cca3: 'CAN',
    region: 'Americas',
    subregion: 'North America',
    lat: 60.000000,
    lng: -95.000000,
    capital: 'Ottawa',
    languages: ['English', 'French'],
    currencies: ['Canadian dollar (\$)'],
    flag: '🇨🇦',
  ),
  WorldCountryData(
    name: 'Cape Verde',
    cca2: 'CV',
    cca3: 'CPV',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 16.000000,
    lng: -24.000000,
    capital: 'Praia',
    languages: ['Portuguese'],
    currencies: ['Cape Verdean escudo (Esc)'],
    flag: '🇨🇻',
  ),
  WorldCountryData(
    name: 'Caribbean Netherlands',
    cca2: 'BQ',
    cca3: 'BES',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 12.180000,
    lng: -68.250000,
    capital: 'Kralendijk',
    languages: ['English', 'Dutch', 'Papiamento'],
    currencies: ['United States dollar (\$)'],
    flag: null,
  ),
  WorldCountryData(
    name: 'Cayman Islands',
    cca2: 'KY',
    cca3: 'CYM',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 19.500000,
    lng: -80.500000,
    capital: 'George Town',
    languages: ['English'],
    currencies: ['Cayman Islands dollar (\$)'],
    flag: '🇰🇾',
  ),
  WorldCountryData(
    name: 'Central African Republic',
    cca2: 'CF',
    cca3: 'CAF',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: 7.000000,
    lng: 21.000000,
    capital: 'Bangui',
    languages: ['French', 'Sango'],
    currencies: ['Central African CFA franc (Fr)'],
    flag: '🇨🇫',
  ),
  WorldCountryData(
    name: 'Chad',
    cca2: 'TD',
    cca3: 'TCD',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: 15.000000,
    lng: 19.000000,
    capital: 'N\'Djamena',
    languages: ['Arabic', 'French'],
    currencies: ['Central African CFA franc (Fr)'],
    flag: '🇹🇩',
  ),
  WorldCountryData(
    name: 'Chile',
    cca2: 'CL',
    cca3: 'CHL',
    region: 'Americas',
    subregion: 'South America',
    lat: -30.000000,
    lng: -71.000000,
    capital: 'Santiago',
    languages: ['Spanish'],
    currencies: ['Chilean peso (\$)'],
    flag: '🇨🇱',
  ),
  WorldCountryData(
    name: 'China',
    cca2: 'CN',
    cca3: 'CHN',
    region: 'Asia',
    subregion: 'Eastern Asia',
    lat: 35.000000,
    lng: 105.000000,
    capital: 'Beijing',
    languages: ['Chinese'],
    currencies: ['Chinese yuan (¥)'],
    flag: '🇨🇳',
  ),
  WorldCountryData(
    name: 'Christmas Island',
    cca2: 'CX',
    cca3: 'CXR',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    lat: -10.500000,
    lng: 105.666667,
    capital: 'Flying Fish Cove',
    languages: ['English'],
    currencies: ['Australian dollar (\$)'],
    flag: '🇨🇽',
  ),
  WorldCountryData(
    name: 'Cocos (Keeling) Islands',
    cca2: 'CC',
    cca3: 'CCK',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    lat: -12.500000,
    lng: 96.833333,
    capital: 'West Island',
    languages: ['English'],
    currencies: ['Australian dollar (\$)'],
    flag: '🇨🇨',
  ),
  WorldCountryData(
    name: 'Colombia',
    cca2: 'CO',
    cca3: 'COL',
    region: 'Americas',
    subregion: 'South America',
    lat: 4.000000,
    lng: -72.000000,
    capital: 'Bogotá',
    languages: ['Spanish'],
    currencies: ['Colombian peso (\$)'],
    flag: '🇨🇴',
  ),
  WorldCountryData(
    name: 'Comoros',
    cca2: 'KM',
    cca3: 'COM',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -12.166667,
    lng: 44.250000,
    capital: 'Moroni',
    languages: ['Arabic', 'French', 'Comorian'],
    currencies: ['Comorian franc (Fr)'],
    flag: '🇰🇲',
  ),
  WorldCountryData(
    name: 'Cook Islands',
    cca2: 'CK',
    cca3: 'COK',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -21.233333,
    lng: -159.766667,
    capital: 'Avarua',
    languages: ['English', 'Cook Islands Māori'],
    currencies: ['Cook Islands dollar (\$)', 'New Zealand dollar (\$)'],
    flag: '🇨🇰',
  ),
  WorldCountryData(
    name: 'Costa Rica',
    cca2: 'CR',
    cca3: 'CRI',
    region: 'Americas',
    subregion: 'Central America',
    lat: 10.000000,
    lng: -84.000000,
    capital: 'San José',
    languages: ['Spanish'],
    currencies: ['Costa Rican colón (₡)'],
    flag: '🇨🇷',
  ),
  WorldCountryData(
    name: 'Croatia',
    cca2: 'HR',
    cca3: 'HRV',
    region: 'Europe',
    subregion: 'Southeast Europe',
    lat: 45.166667,
    lng: 15.500000,
    capital: 'Zagreb',
    languages: ['Croatian'],
    currencies: ['Euro (€)'],
    flag: '🇭🇷',
  ),
  WorldCountryData(
    name: 'Cuba',
    cca2: 'CU',
    cca3: 'CUB',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 21.500000,
    lng: -80.000000,
    capital: 'Havana',
    languages: ['Spanish'],
    currencies: ['Cuban convertible peso (\$)', 'Cuban peso (\$)'],
    flag: '🇨🇺',
  ),
  WorldCountryData(
    name: 'Curaçao',
    cca2: 'CW',
    cca3: 'CUW',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 12.116667,
    lng: -68.933333,
    capital: 'Willemstad',
    languages: ['English', 'Dutch', 'Papiamento'],
    currencies: ['Netherlands Antillean guilder (ƒ)'],
    flag: '🇨🇼',
  ),
  WorldCountryData(
    name: 'Cyprus',
    cca2: 'CY',
    cca3: 'CYP',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 35.000000,
    lng: 33.000000,
    capital: 'Nicosia',
    languages: ['Greek', 'Turkish'],
    currencies: ['Euro (€)'],
    flag: '🇨🇾',
  ),
  WorldCountryData(
    name: 'Czechia',
    cca2: 'CZ',
    cca3: 'CZE',
    region: 'Europe',
    subregion: 'Central Europe',
    lat: 49.750000,
    lng: 15.500000,
    capital: 'Prague',
    languages: ['Czech', 'Slovak'],
    currencies: ['Czech koruna (Kč)'],
    flag: '🇨🇿',
  ),
  WorldCountryData(
    name: 'Denmark',
    cca2: 'DK',
    cca3: 'DNK',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 56.000000,
    lng: 10.000000,
    capital: 'Copenhagen',
    languages: ['Danish'],
    currencies: ['Danish krone (kr)'],
    flag: '🇩🇰',
  ),
  WorldCountryData(
    name: 'Djibouti',
    cca2: 'DJ',
    cca3: 'DJI',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: 11.500000,
    lng: 43.000000,
    capital: 'Djibouti',
    languages: ['Arabic', 'French'],
    currencies: ['Djiboutian franc (Fr)'],
    flag: '🇩🇯',
  ),
  WorldCountryData(
    name: 'Dominica',
    cca2: 'DM',
    cca3: 'DMA',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 15.416667,
    lng: -61.333333,
    capital: 'Roseau',
    languages: ['English'],
    currencies: ['Eastern Caribbean dollar (\$)'],
    flag: '🇩🇲',
  ),
  WorldCountryData(
    name: 'Dominican Republic',
    cca2: 'DO',
    cca3: 'DOM',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 19.000000,
    lng: -70.666667,
    capital: 'Santo Domingo',
    languages: ['Spanish'],
    currencies: ['Dominican peso (\$)'],
    flag: '🇩🇴',
  ),
  WorldCountryData(
    name: 'DR Congo',
    cca2: 'CD',
    cca3: 'COD',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: 0.000000,
    lng: 25.000000,
    capital: 'Kinshasa',
    languages: ['French', 'Kikongo', 'Lingala', 'Tshiluba', 'Swahili'],
    currencies: ['Congolese franc (FC)'],
    flag: '🇨🇩',
  ),
  WorldCountryData(
    name: 'Ecuador',
    cca2: 'EC',
    cca3: 'ECU',
    region: 'Americas',
    subregion: 'South America',
    lat: -2.000000,
    lng: -77.500000,
    capital: 'Quito',
    languages: ['Spanish'],
    currencies: ['United States dollar (\$)'],
    flag: '🇪🇨',
  ),
  WorldCountryData(
    name: 'Egypt',
    cca2: 'EG',
    cca3: 'EGY',
    region: 'Africa',
    subregion: 'Northern Africa',
    lat: 27.000000,
    lng: 30.000000,
    capital: 'Cairo',
    languages: ['Arabic'],
    currencies: ['Egyptian pound (£)'],
    flag: '🇪🇬',
  ),
  WorldCountryData(
    name: 'El Salvador',
    cca2: 'SV',
    cca3: 'SLV',
    region: 'Americas',
    subregion: 'Central America',
    lat: 13.833333,
    lng: -88.916667,
    capital: 'San Salvador',
    languages: ['Spanish'],
    currencies: ['United States dollar (\$)'],
    flag: '🇸🇻',
  ),
  WorldCountryData(
    name: 'Equatorial Guinea',
    cca2: 'GQ',
    cca3: 'GNQ',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: 2.000000,
    lng: 10.000000,
    capital: 'Malabo',
    languages: ['French', 'Portuguese', 'Spanish'],
    currencies: ['Central African CFA franc (Fr)'],
    flag: '🇬🇶',
  ),
  WorldCountryData(
    name: 'Eritrea',
    cca2: 'ER',
    cca3: 'ERI',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: 15.000000,
    lng: 39.000000,
    capital: 'Asmara',
    languages: ['Arabic', 'English', 'Tigrinya'],
    currencies: ['Eritrean nakfa (Nfk)'],
    flag: '🇪🇷',
  ),
  WorldCountryData(
    name: 'Estonia',
    cca2: 'EE',
    cca3: 'EST',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 59.000000,
    lng: 26.000000,
    capital: 'Tallinn',
    languages: ['Estonian'],
    currencies: ['Euro (€)'],
    flag: '🇪🇪',
  ),
  WorldCountryData(
    name: 'Eswatini',
    cca2: 'SZ',
    cca3: 'SWZ',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -26.500000,
    lng: 31.500000,
    capital: 'Lobamba',
    languages: ['English', 'Swazi'],
    currencies: ['Swazi lilangeni (L)', 'South African rand (R)'],
    flag: '🇸🇿',
  ),
  WorldCountryData(
    name: 'Ethiopia',
    cca2: 'ET',
    cca3: 'ETH',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: 8.000000,
    lng: 38.000000,
    capital: 'Addis Ababa',
    languages: ['Amharic'],
    currencies: ['Ethiopian birr (Br)'],
    flag: '🇪🇹',
  ),
  WorldCountryData(
    name: 'Falkland Islands',
    cca2: 'FK',
    cca3: 'FLK',
    region: 'Americas',
    subregion: 'South America',
    lat: -51.750000,
    lng: -59.000000,
    capital: 'Stanley',
    languages: ['English'],
    currencies: ['Falkland Islands pound (£)'],
    flag: '🇫🇰',
  ),
  WorldCountryData(
    name: 'Faroe Islands',
    cca2: 'FO',
    cca3: 'FRO',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 62.000000,
    lng: -7.000000,
    capital: 'Tórshavn',
    languages: ['Danish', 'Faroese'],
    currencies: ['Danish krone (kr)', 'Faroese króna (kr)'],
    flag: '🇫🇴',
  ),
  WorldCountryData(
    name: 'Fiji',
    cca2: 'FJ',
    cca3: 'FJI',
    region: 'Oceania',
    subregion: 'Melanesia',
    lat: -18.000000,
    lng: 175.000000,
    capital: 'Suva',
    languages: ['English', 'Fijian', 'Fiji Hindi'],
    currencies: ['Fijian dollar (\$)'],
    flag: '🇫🇯',
  ),
  WorldCountryData(
    name: 'Finland',
    cca2: 'FI',
    cca3: 'FIN',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 64.000000,
    lng: 26.000000,
    capital: 'Helsinki',
    languages: ['Finnish', 'Swedish'],
    currencies: ['Euro (€)'],
    flag: '🇫🇮',
  ),
  WorldCountryData(
    name: 'France',
    cca2: 'FR',
    cca3: 'FRA',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 46.000000,
    lng: 2.000000,
    capital: 'Paris',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇫🇷',
  ),
  WorldCountryData(
    name: 'French Guiana',
    cca2: 'GF',
    cca3: 'GUF',
    region: 'Americas',
    subregion: 'South America',
    lat: 4.000000,
    lng: -53.000000,
    capital: 'Cayenne',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇬🇫',
  ),
  WorldCountryData(
    name: 'French Polynesia',
    cca2: 'PF',
    cca3: 'PYF',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -15.000000,
    lng: -140.000000,
    capital: 'Papeetē',
    languages: ['French'],
    currencies: ['CFP franc (₣)'],
    flag: '🇵🇫',
  ),
  WorldCountryData(
    name: 'French Southern and Antarctic Lands',
    cca2: 'TF',
    cca3: 'ATF',
    region: 'Antarctic',
    subregion: '',
    lat: -49.250000,
    lng: 69.167000,
    capital: 'Port-aux-Français',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇹🇫',
  ),
  WorldCountryData(
    name: 'Gabon',
    cca2: 'GA',
    cca3: 'GAB',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: -1.000000,
    lng: 11.750000,
    capital: 'Libreville',
    languages: ['French'],
    currencies: ['Central African CFA franc (Fr)'],
    flag: '🇬🇦',
  ),
  WorldCountryData(
    name: 'Gambia',
    cca2: 'GM',
    cca3: 'GMB',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 13.466667,
    lng: -16.566667,
    capital: 'Banjul',
    languages: ['English'],
    currencies: ['dalasi (D)'],
    flag: '🇬🇲',
  ),
  WorldCountryData(
    name: 'Georgia',
    cca2: 'GE',
    cca3: 'GEO',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 42.000000,
    lng: 43.500000,
    capital: 'Tbilisi',
    languages: ['Georgian'],
    currencies: ['lari (₾)'],
    flag: '🇬🇪',
  ),
  WorldCountryData(
    name: 'Germany',
    cca2: 'DE',
    cca3: 'DEU',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 51.000000,
    lng: 9.000000,
    capital: 'Berlin',
    languages: ['German'],
    currencies: ['Euro (€)'],
    flag: '🇩🇪',
  ),
  WorldCountryData(
    name: 'Ghana',
    cca2: 'GH',
    cca3: 'GHA',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 8.000000,
    lng: -2.000000,
    capital: 'Accra',
    languages: ['English'],
    currencies: ['Ghanaian cedi (₵)'],
    flag: '🇬🇭',
  ),
  WorldCountryData(
    name: 'Gibraltar',
    cca2: 'GI',
    cca3: 'GIB',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 36.133333,
    lng: -5.350000,
    capital: 'Gibraltar',
    languages: ['English'],
    currencies: ['Gibraltar pound (£)'],
    flag: '🇬🇮',
  ),
  WorldCountryData(
    name: 'Greece',
    cca2: 'GR',
    cca3: 'GRC',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 39.000000,
    lng: 22.000000,
    capital: 'Athens',
    languages: ['Greek'],
    currencies: ['Euro (€)'],
    flag: '🇬🇷',
  ),
  WorldCountryData(
    name: 'Greenland',
    cca2: 'GL',
    cca3: 'GRL',
    region: 'Americas',
    subregion: 'North America',
    lat: 72.000000,
    lng: -40.000000,
    capital: 'Nuuk',
    languages: ['Greenlandic'],
    currencies: ['krone (kr.)'],
    flag: '🇬🇱',
  ),
  WorldCountryData(
    name: 'Grenada',
    cca2: 'GD',
    cca3: 'GRD',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 12.116667,
    lng: -61.666667,
    capital: 'St. George\'s',
    languages: ['English'],
    currencies: ['Eastern Caribbean dollar (\$)'],
    flag: '🇬🇩',
  ),
  WorldCountryData(
    name: 'Guadeloupe',
    cca2: 'GP',
    cca3: 'GLP',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 16.250000,
    lng: -61.583333,
    capital: 'Basse-Terre',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇬🇵',
  ),
  WorldCountryData(
    name: 'Guam',
    cca2: 'GU',
    cca3: 'GUM',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 13.466667,
    lng: 144.783333,
    capital: 'Hagåtña',
    languages: ['Chamorro', 'English', 'Spanish'],
    currencies: ['United States dollar (\$)'],
    flag: '🇬🇺',
  ),
  WorldCountryData(
    name: 'Guatemala',
    cca2: 'GT',
    cca3: 'GTM',
    region: 'Americas',
    subregion: 'Central America',
    lat: 15.500000,
    lng: -90.250000,
    capital: 'Guatemala City',
    languages: ['Spanish'],
    currencies: ['Guatemalan quetzal (Q)'],
    flag: '🇬🇹',
  ),
  WorldCountryData(
    name: 'Guernsey',
    cca2: 'GG',
    cca3: 'GGY',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 49.466667,
    lng: -2.583333,
    capital: 'St. Peter Port',
    languages: ['English', 'French', 'Guernésiais'],
    currencies: ['British pound (£)', 'Guernsey pound (£)'],
    flag: '🇬🇬',
  ),
  WorldCountryData(
    name: 'Guinea',
    cca2: 'GN',
    cca3: 'GIN',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 11.000000,
    lng: -10.000000,
    capital: 'Conakry',
    languages: ['French'],
    currencies: ['Guinean franc (Fr)'],
    flag: '🇬🇳',
  ),
  WorldCountryData(
    name: 'Guinea-Bissau',
    cca2: 'GW',
    cca3: 'GNB',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 12.000000,
    lng: -15.000000,
    capital: 'Bissau',
    languages: ['Portuguese', 'Upper Guinea Creole'],
    currencies: ['West African CFA franc (Fr)'],
    flag: '🇬🇼',
  ),
  WorldCountryData(
    name: 'Guyana',
    cca2: 'GY',
    cca3: 'GUY',
    region: 'Americas',
    subregion: 'South America',
    lat: 5.000000,
    lng: -59.000000,
    capital: 'Georgetown',
    languages: ['English'],
    currencies: ['Guyanese dollar (\$)'],
    flag: '🇬🇾',
  ),
  WorldCountryData(
    name: 'Haiti',
    cca2: 'HT',
    cca3: 'HTI',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 19.000000,
    lng: -72.416667,
    capital: 'Port-au-Prince',
    languages: ['French', 'Haitian Creole'],
    currencies: ['Haitian gourde (G)'],
    flag: '🇭🇹',
  ),
  WorldCountryData(
    name: 'Heard Island and McDonald Islands',
    cca2: 'HM',
    cca3: 'HMD',
    region: 'Antarctic',
    subregion: '',
    lat: -53.100000,
    lng: 72.516667,
    capital: null,
    languages: ['English'],
    currencies: [],
    flag: '🇭🇲',
  ),
  WorldCountryData(
    name: 'Honduras',
    cca2: 'HN',
    cca3: 'HND',
    region: 'Americas',
    subregion: 'Central America',
    lat: 15.000000,
    lng: -86.500000,
    capital: 'Tegucigalpa',
    languages: ['Spanish'],
    currencies: ['Honduran lempira (L)'],
    flag: '🇭🇳',
  ),
  WorldCountryData(
    name: 'Hong Kong',
    cca2: 'HK',
    cca3: 'HKG',
    region: 'Asia',
    subregion: 'Eastern Asia',
    lat: 22.267000,
    lng: 114.188000,
    capital: 'City of Victoria',
    languages: ['English', 'Chinese'],
    currencies: ['Hong Kong dollar (\$)'],
    flag: '🇭🇰',
  ),
  WorldCountryData(
    name: 'Hungary',
    cca2: 'HU',
    cca3: 'HUN',
    region: 'Europe',
    subregion: 'Central Europe',
    lat: 47.000000,
    lng: 20.000000,
    capital: 'Budapest',
    languages: ['Hungarian'],
    currencies: ['Hungarian forint (Ft)'],
    flag: '🇭🇺',
  ),
  WorldCountryData(
    name: 'Iceland',
    cca2: 'IS',
    cca3: 'ISL',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 65.000000,
    lng: -18.000000,
    capital: 'Reykjavik',
    languages: ['Icelandic'],
    currencies: ['Icelandic króna (kr)'],
    flag: '🇮🇸',
  ),
  WorldCountryData(
    name: 'India',
    cca2: 'IN',
    cca3: 'IND',
    region: 'Asia',
    subregion: 'Southern Asia',
    lat: 20.000000,
    lng: 77.000000,
    capital: 'New Delhi',
    languages: ['English', 'Hindi', 'Tamil'],
    currencies: ['Indian rupee (₹)'],
    flag: '🇮🇳',
  ),
  WorldCountryData(
    name: 'Indonesia',
    cca2: 'ID',
    cca3: 'IDN',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: -5.000000,
    lng: 120.000000,
    capital: 'Jakarta',
    languages: ['Indonesian'],
    currencies: ['Indonesian rupiah (Rp)'],
    flag: '🇮🇩',
  ),
  WorldCountryData(
    name: 'Iran',
    cca2: 'IR',
    cca3: 'IRN',
    region: 'Asia',
    subregion: 'Southern Asia',
    lat: 32.000000,
    lng: 53.000000,
    capital: 'Tehran',
    languages: ['Persian (Farsi)'],
    currencies: ['Iranian rial (﷼)'],
    flag: '🇮🇷',
  ),
  WorldCountryData(
    name: 'Iraq',
    cca2: 'IQ',
    cca3: 'IRQ',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 33.000000,
    lng: 44.000000,
    capital: 'Baghdad',
    languages: ['Arabic', 'Aramaic', 'Sorani'],
    currencies: ['Iraqi dinar (ع.د)'],
    flag: '🇮🇶',
  ),
  WorldCountryData(
    name: 'Ireland',
    cca2: 'IE',
    cca3: 'IRL',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 53.000000,
    lng: -8.000000,
    capital: 'Dublin',
    languages: ['English', 'Irish'],
    currencies: ['Euro (€)'],
    flag: '🇮🇪',
  ),
  WorldCountryData(
    name: 'Isle of Man',
    cca2: 'IM',
    cca3: 'IMN',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 54.250000,
    lng: -4.500000,
    capital: 'Douglas',
    languages: ['English', 'Manx'],
    currencies: ['British pound (£)', 'Manx pound (£)'],
    flag: '🇮🇲',
  ),
  WorldCountryData(
    name: 'Israel',
    cca2: 'IL',
    cca3: 'ISR',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 31.470000,
    lng: 35.130000,
    capital: 'Jerusalem',
    languages: ['Arabic', 'Hebrew'],
    currencies: ['Israeli new shekel (₪)'],
    flag: '🇮🇱',
  ),
  WorldCountryData(
    name: 'Italy',
    cca2: 'IT',
    cca3: 'ITA',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 42.833333,
    lng: 12.833333,
    capital: 'Rome',
    languages: ['Italian'],
    currencies: ['Euro (€)'],
    flag: '🇮🇹',
  ),
  WorldCountryData(
    name: 'Ivory Coast',
    cca2: 'CI',
    cca3: 'CIV',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 8.000000,
    lng: -5.000000,
    capital: 'Yamoussoukro',
    languages: ['French'],
    currencies: ['West African CFA franc (Fr)'],
    flag: '🇨🇮',
  ),
  WorldCountryData(
    name: 'Jamaica',
    cca2: 'JM',
    cca3: 'JAM',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.250000,
    lng: -77.500000,
    capital: 'Kingston',
    languages: ['English', 'Jamaican Patois'],
    currencies: ['Jamaican dollar (\$)'],
    flag: '🇯🇲',
  ),
  WorldCountryData(
    name: 'Japan',
    cca2: 'JP',
    cca3: 'JPN',
    region: 'Asia',
    subregion: 'Eastern Asia',
    lat: 36.000000,
    lng: 138.000000,
    capital: 'Tokyo',
    languages: ['Japanese'],
    currencies: ['Japanese yen (¥)'],
    flag: '🇯🇵',
  ),
  WorldCountryData(
    name: 'Jersey',
    cca2: 'JE',
    cca3: 'JEY',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 49.250000,
    lng: -2.166667,
    capital: 'Saint Helier',
    languages: ['English', 'French', 'Jèrriais'],
    currencies: ['British pound (£)', 'Jersey pound (£)'],
    flag: '🇯🇪',
  ),
  WorldCountryData(
    name: 'Jordan',
    cca2: 'JO',
    cca3: 'JOR',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 31.000000,
    lng: 36.000000,
    capital: 'Amman',
    languages: ['Arabic'],
    currencies: ['Jordanian dinar (د.ا)'],
    flag: '🇯🇴',
  ),
  WorldCountryData(
    name: 'Kazakhstan',
    cca2: 'KZ',
    cca3: 'KAZ',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 48.000000,
    lng: 68.000000,
    capital: 'Astana',
    languages: ['Kazakh', 'Russian'],
    currencies: ['Kazakhstani tenge (₸)'],
    flag: '🇰🇿',
  ),
  WorldCountryData(
    name: 'Kenya',
    cca2: 'KE',
    cca3: 'KEN',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: 1.000000,
    lng: 38.000000,
    capital: 'Nairobi',
    languages: ['English', 'Swahili'],
    currencies: ['Kenyan shilling (Sh)'],
    flag: '🇰🇪',
  ),
  WorldCountryData(
    name: 'Kiribati',
    cca2: 'KI',
    cca3: 'KIR',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 1.416667,
    lng: 173.000000,
    capital: 'South Tarawa',
    languages: ['English', 'Gilbertese'],
    currencies: ['Australian dollar (\$)', 'Kiribati dollar (\$)'],
    flag: '🇰🇮',
  ),
  WorldCountryData(
    name: 'Kosovo',
    cca2: 'XK',
    cca3: 'UNK',
    region: 'Europe',
    subregion: 'Southeast Europe',
    lat: 42.666667,
    lng: 21.166667,
    capital: 'Pristina',
    languages: ['Albanian', 'Serbian'],
    currencies: ['Euro (€)'],
    flag: '🇽🇰',
  ),
  WorldCountryData(
    name: 'Kuwait',
    cca2: 'KW',
    cca3: 'KWT',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 29.500000,
    lng: 45.750000,
    capital: 'Kuwait City',
    languages: ['Arabic'],
    currencies: ['Kuwaiti dinar (د.ك)'],
    flag: '🇰🇼',
  ),
  WorldCountryData(
    name: 'Kyrgyzstan',
    cca2: 'KG',
    cca3: 'KGZ',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 41.000000,
    lng: 75.000000,
    capital: 'Bishkek',
    languages: ['Kyrgyz', 'Russian'],
    currencies: ['Kyrgyzstani som (с)'],
    flag: '🇰🇬',
  ),
  WorldCountryData(
    name: 'Laos',
    cca2: 'LA',
    cca3: 'LAO',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: 18.000000,
    lng: 105.000000,
    capital: 'Vientiane',
    languages: ['Lao'],
    currencies: ['Lao kip (₭)'],
    flag: '🇱🇦',
  ),
  WorldCountryData(
    name: 'Latvia',
    cca2: 'LV',
    cca3: 'LVA',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 57.000000,
    lng: 25.000000,
    capital: 'Riga',
    languages: ['Latvian'],
    currencies: ['Euro (€)'],
    flag: '🇱🇻',
  ),
  WorldCountryData(
    name: 'Lebanon',
    cca2: 'LB',
    cca3: 'LBN',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 33.833333,
    lng: 35.833333,
    capital: 'Beirut',
    languages: ['Arabic', 'French'],
    currencies: ['Lebanese pound (ل.ل)'],
    flag: '🇱🇧',
  ),
  WorldCountryData(
    name: 'Lesotho',
    cca2: 'LS',
    cca3: 'LSO',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -29.500000,
    lng: 28.500000,
    capital: 'Maseru',
    languages: ['English', 'Sotho'],
    currencies: ['Lesotho loti (L)', 'South African rand (R)'],
    flag: '🇱🇸',
  ),
  WorldCountryData(
    name: 'Liberia',
    cca2: 'LR',
    cca3: 'LBR',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 6.500000,
    lng: -9.500000,
    capital: 'Monrovia',
    languages: ['English'],
    currencies: ['Liberian dollar (\$)'],
    flag: '🇱🇷',
  ),
  WorldCountryData(
    name: 'Libya',
    cca2: 'LY',
    cca3: 'LBY',
    region: 'Africa',
    subregion: 'Northern Africa',
    lat: 25.000000,
    lng: 17.000000,
    capital: 'Tripoli',
    languages: ['Arabic'],
    currencies: ['Libyan dinar (ل.د)'],
    flag: '🇱🇾',
  ),
  WorldCountryData(
    name: 'Liechtenstein',
    cca2: 'LI',
    cca3: 'LIE',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 47.266667,
    lng: 9.533333,
    capital: 'Vaduz',
    languages: ['German'],
    currencies: ['Swiss franc (Fr)'],
    flag: '🇱🇮',
  ),
  WorldCountryData(
    name: 'Lithuania',
    cca2: 'LT',
    cca3: 'LTU',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 56.000000,
    lng: 24.000000,
    capital: 'Vilnius',
    languages: ['Lithuanian'],
    currencies: ['Euro (€)'],
    flag: '🇱🇹',
  ),
  WorldCountryData(
    name: 'Luxembourg',
    cca2: 'LU',
    cca3: 'LUX',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 49.750000,
    lng: 6.166667,
    capital: 'Luxembourg',
    languages: ['German', 'French', 'Luxembourgish'],
    currencies: ['Euro (€)'],
    flag: '🇱🇺',
  ),
  WorldCountryData(
    name: 'Macau',
    cca2: 'MO',
    cca3: 'MAC',
    region: 'Asia',
    subregion: 'Eastern Asia',
    lat: 22.166667,
    lng: 113.550000,
    capital: null,
    languages: ['Portuguese', 'Chinese'],
    currencies: ['Macanese pataca (P)'],
    flag: '🇲🇴',
  ),
  WorldCountryData(
    name: 'Madagascar',
    cca2: 'MG',
    cca3: 'MDG',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -20.000000,
    lng: 47.000000,
    capital: 'Antananarivo',
    languages: ['French', 'Malagasy'],
    currencies: ['Malagasy ariary (Ar)'],
    flag: '🇲🇬',
  ),
  WorldCountryData(
    name: 'Malawi',
    cca2: 'MW',
    cca3: 'MWI',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -13.500000,
    lng: 34.000000,
    capital: 'Lilongwe',
    languages: ['English', 'Chewa'],
    currencies: ['Malawian kwacha (MK)'],
    flag: '🇲🇼',
  ),
  WorldCountryData(
    name: 'Malaysia',
    cca2: 'MY',
    cca3: 'MYS',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: 2.500000,
    lng: 112.500000,
    capital: 'Kuala Lumpur',
    languages: ['English', 'Malay'],
    currencies: ['Malaysian ringgit (RM)'],
    flag: '🇲🇾',
  ),
  WorldCountryData(
    name: 'Maldives',
    cca2: 'MV',
    cca3: 'MDV',
    region: 'Asia',
    subregion: 'Southern Asia',
    lat: 3.250000,
    lng: 73.000000,
    capital: 'Malé',
    languages: ['Maldivian'],
    currencies: ['Maldivian rufiyaa (.ރ)'],
    flag: '🇲🇻',
  ),
  WorldCountryData(
    name: 'Mali',
    cca2: 'ML',
    cca3: 'MLI',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 17.000000,
    lng: -4.000000,
    capital: 'Bamako',
    languages: ['French'],
    currencies: ['West African CFA franc (Fr)'],
    flag: '🇲🇱',
  ),
  WorldCountryData(
    name: 'Malta',
    cca2: 'MT',
    cca3: 'MLT',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 35.833333,
    lng: 14.583333,
    capital: 'Valletta',
    languages: ['English', 'Maltese'],
    currencies: ['Euro (€)'],
    flag: '🇲🇹',
  ),
  WorldCountryData(
    name: 'Marshall Islands',
    cca2: 'MH',
    cca3: 'MHL',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 9.000000,
    lng: 168.000000,
    capital: 'Majuro',
    languages: ['English', 'Marshallese'],
    currencies: ['United States dollar (\$)'],
    flag: '🇲🇭',
  ),
  WorldCountryData(
    name: 'Martinique',
    cca2: 'MQ',
    cca3: 'MTQ',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 14.666667,
    lng: -61.000000,
    capital: 'Fort-de-France',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇲🇶',
  ),
  WorldCountryData(
    name: 'Mauritania',
    cca2: 'MR',
    cca3: 'MRT',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 20.000000,
    lng: -12.000000,
    capital: 'Nouakchott',
    languages: ['Arabic'],
    currencies: ['Mauritanian ouguiya (UM)'],
    flag: '🇲🇷',
  ),
  WorldCountryData(
    name: 'Mauritius',
    cca2: 'MU',
    cca3: 'MUS',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -20.283333,
    lng: 57.550000,
    capital: 'Port Louis',
    languages: ['English', 'French', 'Mauritian Creole'],
    currencies: ['Mauritian rupee (₨)'],
    flag: '🇲🇺',
  ),
  WorldCountryData(
    name: 'Mayotte',
    cca2: 'YT',
    cca3: 'MYT',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -12.833333,
    lng: 45.166667,
    capital: 'Mamoudzou',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇾🇹',
  ),
  WorldCountryData(
    name: 'Mexico',
    cca2: 'MX',
    cca3: 'MEX',
    region: 'Americas',
    subregion: 'North America',
    lat: 23.000000,
    lng: -102.000000,
    capital: 'Mexico City',
    languages: ['Spanish'],
    currencies: ['Mexican peso (\$)'],
    flag: '🇲🇽',
  ),
  WorldCountryData(
    name: 'Micronesia',
    cca2: 'FM',
    cca3: 'FSM',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 6.916667,
    lng: 158.250000,
    capital: 'Palikir',
    languages: ['English'],
    currencies: [],
    flag: '🇫🇲',
  ),
  WorldCountryData(
    name: 'Moldova',
    cca2: 'MD',
    cca3: 'MDA',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 47.000000,
    lng: 29.000000,
    capital: 'Chișinău',
    languages: ['Moldavian'],
    currencies: ['Moldovan leu (L)'],
    flag: '🇲🇩',
  ),
  WorldCountryData(
    name: 'Monaco',
    cca2: 'MC',
    cca3: 'MCO',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 43.733333,
    lng: 7.400000,
    capital: 'Monaco',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇲🇨',
  ),
  WorldCountryData(
    name: 'Mongolia',
    cca2: 'MN',
    cca3: 'MNG',
    region: 'Asia',
    subregion: 'Eastern Asia',
    lat: 46.000000,
    lng: 105.000000,
    capital: 'Ulan Bator',
    languages: ['Mongolian'],
    currencies: ['Mongolian tögrög (₮)'],
    flag: '🇲🇳',
  ),
  WorldCountryData(
    name: 'Montenegro',
    cca2: 'ME',
    cca3: 'MNE',
    region: 'Europe',
    subregion: 'Southeast Europe',
    lat: 42.500000,
    lng: 19.300000,
    capital: 'Podgorica',
    languages: ['Montenegrin'],
    currencies: ['Euro (€)'],
    flag: '🇲🇪',
  ),
  WorldCountryData(
    name: 'Montserrat',
    cca2: 'MS',
    cca3: 'MSR',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 16.750000,
    lng: -62.200000,
    capital: 'Plymouth',
    languages: ['English'],
    currencies: ['Eastern Caribbean dollar (\$)'],
    flag: '🇲🇸',
  ),
  WorldCountryData(
    name: 'Morocco',
    cca2: 'MA',
    cca3: 'MAR',
    region: 'Africa',
    subregion: 'Northern Africa',
    lat: 32.000000,
    lng: -5.000000,
    capital: 'Rabat',
    languages: ['Arabic', 'Berber'],
    currencies: ['Moroccan dirham (د.م.)'],
    flag: '🇲🇦',
  ),
  WorldCountryData(
    name: 'Mozambique',
    cca2: 'MZ',
    cca3: 'MOZ',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -18.250000,
    lng: 35.000000,
    capital: 'Maputo',
    languages: ['Portuguese'],
    currencies: ['Mozambican metical (MT)'],
    flag: '🇲🇿',
  ),
  WorldCountryData(
    name: 'Myanmar',
    cca2: 'MM',
    cca3: 'MMR',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: 22.000000,
    lng: 98.000000,
    capital: 'Naypyidaw',
    languages: ['Burmese'],
    currencies: ['Burmese kyat (Ks)'],
    flag: '🇲🇲',
  ),
  WorldCountryData(
    name: 'Namibia',
    cca2: 'NA',
    cca3: 'NAM',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -22.000000,
    lng: 17.000000,
    capital: 'Windhoek',
    languages: [
      'Afrikaans',
      'German',
      'English',
      'Herero',
      'Khoekhoe',
      'Kwangali',
      'Lozi',
      'Ndonga',
      'Tswana',
    ],
    currencies: ['Namibian dollar (\$)', 'South African rand (R)'],
    flag: '🇳🇦',
  ),
  WorldCountryData(
    name: 'Nauru',
    cca2: 'NR',
    cca3: 'NRU',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: -0.533333,
    lng: 166.916667,
    capital: 'Yaren',
    languages: ['English', 'Nauru'],
    currencies: ['Australian dollar (\$)'],
    flag: '🇳🇷',
  ),
  WorldCountryData(
    name: 'Nepal',
    cca2: 'NP',
    cca3: 'NPL',
    region: 'Asia',
    subregion: 'Southern Asia',
    lat: 28.000000,
    lng: 84.000000,
    capital: 'Kathmandu',
    languages: ['Nepali'],
    currencies: ['Nepalese rupee (₨)'],
    flag: '🇳🇵',
  ),
  WorldCountryData(
    name: 'Netherlands',
    cca2: 'NL',
    cca3: 'NLD',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 52.500000,
    lng: 5.750000,
    capital: 'Amsterdam',
    languages: ['Dutch'],
    currencies: ['Euro (€)'],
    flag: '🇳🇱',
  ),
  WorldCountryData(
    name: 'New Caledonia',
    cca2: 'NC',
    cca3: 'NCL',
    region: 'Oceania',
    subregion: 'Melanesia',
    lat: -21.500000,
    lng: 165.500000,
    capital: 'Nouméa',
    languages: ['French'],
    currencies: ['CFP franc (₣)'],
    flag: '🇳🇨',
  ),
  WorldCountryData(
    name: 'New Zealand',
    cca2: 'NZ',
    cca3: 'NZL',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    lat: -41.000000,
    lng: 174.000000,
    capital: 'Wellington',
    languages: ['English', 'Māori', 'New Zealand Sign Language'],
    currencies: ['New Zealand dollar (\$)'],
    flag: '🇳🇿',
  ),
  WorldCountryData(
    name: 'Nicaragua',
    cca2: 'NI',
    cca3: 'NIC',
    region: 'Americas',
    subregion: 'Central America',
    lat: 13.000000,
    lng: -85.000000,
    capital: 'Managua',
    languages: ['Spanish'],
    currencies: ['Nicaraguan córdoba (C\$)'],
    flag: '🇳🇮',
  ),
  WorldCountryData(
    name: 'Niger',
    cca2: 'NE',
    cca3: 'NER',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 16.000000,
    lng: 8.000000,
    capital: 'Niamey',
    languages: ['French'],
    currencies: ['West African CFA franc (Fr)'],
    flag: '🇳🇪',
  ),
  WorldCountryData(
    name: 'Nigeria',
    cca2: 'NG',
    cca3: 'NGA',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 10.000000,
    lng: 8.000000,
    capital: 'Abuja',
    languages: ['English'],
    currencies: ['Nigerian naira (₦)'],
    flag: '🇳🇬',
  ),
  WorldCountryData(
    name: 'Niue',
    cca2: 'NU',
    cca3: 'NIU',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -19.033333,
    lng: -169.866667,
    capital: 'Alofi',
    languages: ['English', 'Niuean'],
    currencies: ['New Zealand dollar (\$)'],
    flag: '🇳🇺',
  ),
  WorldCountryData(
    name: 'Norfolk Island',
    cca2: 'NF',
    cca3: 'NFK',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    lat: -29.033333,
    lng: 167.950000,
    capital: 'Kingston',
    languages: ['English', 'Norfuk'],
    currencies: ['Australian dollar (\$)'],
    flag: '🇳🇫',
  ),
  WorldCountryData(
    name: 'North Korea',
    cca2: 'KP',
    cca3: 'PRK',
    region: 'Asia',
    subregion: 'Eastern Asia',
    lat: 40.000000,
    lng: 127.000000,
    capital: 'Pyongyang',
    languages: ['Korean'],
    currencies: ['North Korean won (₩)'],
    flag: '🇰🇵',
  ),
  WorldCountryData(
    name: 'North Macedonia',
    cca2: 'MK',
    cca3: 'MKD',
    region: 'Europe',
    subregion: 'Southeast Europe',
    lat: 41.833333,
    lng: 22.000000,
    capital: 'Skopje',
    languages: ['Macedonian'],
    currencies: ['denar (den)'],
    flag: '🇲🇰',
  ),
  WorldCountryData(
    name: 'Northern Mariana Islands',
    cca2: 'MP',
    cca3: 'MNP',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 15.200000,
    lng: 145.750000,
    capital: 'Saipan',
    languages: ['Carolinian', 'Chamorro', 'English'],
    currencies: ['United States dollar (\$)'],
    flag: '🇲🇵',
  ),
  WorldCountryData(
    name: 'Norway',
    cca2: 'NO',
    cca3: 'NOR',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 62.000000,
    lng: 10.000000,
    capital: 'Oslo',
    languages: ['Norwegian Nynorsk', 'Norwegian Bokmål', 'Sami'],
    currencies: ['Norwegian krone (kr)'],
    flag: '🇳🇴',
  ),
  WorldCountryData(
    name: 'Oman',
    cca2: 'OM',
    cca3: 'OMN',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 21.000000,
    lng: 57.000000,
    capital: 'Muscat',
    languages: ['Arabic'],
    currencies: ['Omani rial (ر.ع.)'],
    flag: '🇴🇲',
  ),
  WorldCountryData(
    name: 'Pakistan',
    cca2: 'PK',
    cca3: 'PAK',
    region: 'Asia',
    subregion: 'Southern Asia',
    lat: 30.000000,
    lng: 70.000000,
    capital: 'Islamabad',
    languages: ['English', 'Urdu'],
    currencies: ['Pakistani rupee (₨)'],
    flag: '🇵🇰',
  ),
  WorldCountryData(
    name: 'Palau',
    cca2: 'PW',
    cca3: 'PLW',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 7.500000,
    lng: 134.500000,
    capital: 'Ngerulmud',
    languages: ['English', 'Palauan'],
    currencies: ['United States dollar (\$)'],
    flag: '🇵🇼',
  ),
  WorldCountryData(
    name: 'Palestine',
    cca2: 'PS',
    cca3: 'PSE',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 31.900000,
    lng: 35.200000,
    capital: 'Ramallah',
    languages: ['Arabic'],
    currencies: [
      'Egyptian pound (E£)',
      'Israeli new shekel (₪)',
      'Jordanian dinar (JD)',
    ],
    flag: '🇵🇸',
  ),
  WorldCountryData(
    name: 'Panama',
    cca2: 'PA',
    cca3: 'PAN',
    region: 'Americas',
    subregion: 'Central America',
    lat: 9.000000,
    lng: -80.000000,
    capital: 'Panama City',
    languages: ['Spanish'],
    currencies: ['Panamanian balboa (B/.)', 'United States dollar (\$)'],
    flag: '🇵🇦',
  ),
  WorldCountryData(
    name: 'Papua New Guinea',
    cca2: 'PG',
    cca3: 'PNG',
    region: 'Oceania',
    subregion: 'Melanesia',
    lat: -6.000000,
    lng: 147.000000,
    capital: 'Port Moresby',
    languages: ['English', 'Hiri Motu', 'Tok Pisin'],
    currencies: ['Papua New Guinean kina (K)'],
    flag: '🇵🇬',
  ),
  WorldCountryData(
    name: 'Paraguay',
    cca2: 'PY',
    cca3: 'PRY',
    region: 'Americas',
    subregion: 'South America',
    lat: -23.000000,
    lng: -58.000000,
    capital: 'Asunción',
    languages: ['Guaraní', 'Spanish'],
    currencies: ['Paraguayan guaraní (₲)'],
    flag: '🇵🇾',
  ),
  WorldCountryData(
    name: 'Peru',
    cca2: 'PE',
    cca3: 'PER',
    region: 'Americas',
    subregion: 'South America',
    lat: -10.000000,
    lng: -76.000000,
    capital: 'Lima',
    languages: ['Aymara', 'Quechua', 'Spanish'],
    currencies: ['Peruvian sol (S/.)'],
    flag: '🇵🇪',
  ),
  WorldCountryData(
    name: 'Philippines',
    cca2: 'PH',
    cca3: 'PHL',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: 13.000000,
    lng: 122.000000,
    capital: 'Manila',
    languages: ['English', 'Filipino'],
    currencies: ['Philippine peso (₱)'],
    flag: '🇵🇭',
  ),
  WorldCountryData(
    name: 'Pitcairn Islands',
    cca2: 'PN',
    cca3: 'PCN',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -25.066667,
    lng: -130.100000,
    capital: 'Adamstown',
    languages: ['English'],
    currencies: ['New Zealand dollar (\$)'],
    flag: '🇵🇳',
  ),
  WorldCountryData(
    name: 'Poland',
    cca2: 'PL',
    cca3: 'POL',
    region: 'Europe',
    subregion: 'Central Europe',
    lat: 52.000000,
    lng: 20.000000,
    capital: 'Warsaw',
    languages: ['Polish'],
    currencies: ['Polish złoty (zł)'],
    flag: '🇵🇱',
  ),
  WorldCountryData(
    name: 'Portugal',
    cca2: 'PT',
    cca3: 'PRT',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 39.500000,
    lng: -8.000000,
    capital: 'Lisbon',
    languages: ['Portuguese'],
    currencies: ['Euro (€)'],
    flag: '🇵🇹',
  ),
  WorldCountryData(
    name: 'Puerto Rico',
    cca2: 'PR',
    cca3: 'PRI',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.250000,
    lng: -66.500000,
    capital: 'San Juan',
    languages: ['English', 'Spanish'],
    currencies: ['United States dollar (\$)'],
    flag: '🇵🇷',
  ),
  WorldCountryData(
    name: 'Qatar',
    cca2: 'QA',
    cca3: 'QAT',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 25.500000,
    lng: 51.250000,
    capital: 'Doha',
    languages: ['Arabic'],
    currencies: ['Qatari riyal (ر.ق)'],
    flag: '🇶🇦',
  ),
  WorldCountryData(
    name: 'Republic of the Congo',
    cca2: 'CG',
    cca3: 'COG',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: -1.000000,
    lng: 15.000000,
    capital: 'Brazzaville',
    languages: ['French', 'Kikongo', 'Lingala'],
    currencies: ['Central African CFA franc (Fr)'],
    flag: '🇨🇬',
  ),
  WorldCountryData(
    name: 'Réunion',
    cca2: 'RE',
    cca3: 'REU',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -21.150000,
    lng: 55.500000,
    capital: 'Saint-Denis',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇷🇪',
  ),
  WorldCountryData(
    name: 'Romania',
    cca2: 'RO',
    cca3: 'ROU',
    region: 'Europe',
    subregion: 'Southeast Europe',
    lat: 46.000000,
    lng: 25.000000,
    capital: 'Bucharest',
    languages: ['Romanian'],
    currencies: ['Romanian leu (lei)'],
    flag: '🇷🇴',
  ),
  WorldCountryData(
    name: 'Russia',
    cca2: 'RU',
    cca3: 'RUS',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 60.000000,
    lng: 100.000000,
    capital: 'Moscow',
    languages: ['Russian'],
    currencies: ['Russian ruble (₽)'],
    flag: '🇷🇺',
  ),
  WorldCountryData(
    name: 'Rwanda',
    cca2: 'RW',
    cca3: 'RWA',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -2.000000,
    lng: 30.000000,
    capital: 'Kigali',
    languages: ['English', 'French', 'Kinyarwanda'],
    currencies: ['Rwandan franc (Fr)'],
    flag: '🇷🇼',
  ),
  WorldCountryData(
    name: 'Saint Barthélemy',
    cca2: 'BL',
    cca3: 'BLM',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.500000,
    lng: -63.416667,
    capital: 'Gustavia',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇧🇱',
  ),
  WorldCountryData(
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    cca2: 'SH',
    cca3: 'SHN',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: -15.950000,
    lng: -5.720000,
    capital: 'Jamestown',
    languages: ['English'],
    currencies: ['Pound sterling (£)', 'Saint Helena pound (£)'],
    flag: '🇸🇭',
  ),
  WorldCountryData(
    name: 'Saint Kitts and Nevis',
    cca2: 'KN',
    cca3: 'KNA',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 17.333333,
    lng: -62.750000,
    capital: 'Basseterre',
    languages: ['English'],
    currencies: ['Eastern Caribbean dollar (\$)'],
    flag: '🇰🇳',
  ),
  WorldCountryData(
    name: 'Saint Lucia',
    cca2: 'LC',
    cca3: 'LCA',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 13.883333,
    lng: -60.966667,
    capital: 'Castries',
    languages: ['English'],
    currencies: ['Eastern Caribbean dollar (\$)'],
    flag: '🇱🇨',
  ),
  WorldCountryData(
    name: 'Saint Martin',
    cca2: 'MF',
    cca3: 'MAF',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.083333,
    lng: -63.950000,
    capital: 'Marigot',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇲🇫',
  ),
  WorldCountryData(
    name: 'Saint Pierre and Miquelon',
    cca2: 'PM',
    cca3: 'SPM',
    region: 'Americas',
    subregion: 'North America',
    lat: 46.833333,
    lng: -56.333333,
    capital: 'Saint-Pierre',
    languages: ['French'],
    currencies: ['Euro (€)'],
    flag: '🇵🇲',
  ),
  WorldCountryData(
    name: 'Saint Vincent and the Grenadines',
    cca2: 'VC',
    cca3: 'VCT',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 13.250000,
    lng: -61.200000,
    capital: 'Kingstown',
    languages: ['English'],
    currencies: ['Eastern Caribbean dollar (\$)'],
    flag: '🇻🇨',
  ),
  WorldCountryData(
    name: 'Samoa',
    cca2: 'WS',
    cca3: 'WSM',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -13.583333,
    lng: -172.333333,
    capital: 'Apia',
    languages: ['English', 'Samoan'],
    currencies: ['Samoan tālā (T)'],
    flag: '🇼🇸',
  ),
  WorldCountryData(
    name: 'San Marino',
    cca2: 'SM',
    cca3: 'SMR',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 43.766667,
    lng: 12.416667,
    capital: 'City of San Marino',
    languages: ['Italian'],
    currencies: ['Euro (€)'],
    flag: '🇸🇲',
  ),
  WorldCountryData(
    name: 'São Tomé and Príncipe',
    cca2: 'ST',
    cca3: 'STP',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: 1.000000,
    lng: 7.000000,
    capital: 'São Tomé',
    languages: ['Portuguese'],
    currencies: ['São Tomé and Príncipe dobra (Db)'],
    flag: '🇸🇹',
  ),
  WorldCountryData(
    name: 'Saudi Arabia',
    cca2: 'SA',
    cca3: 'SAU',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 25.000000,
    lng: 45.000000,
    capital: 'Riyadh',
    languages: ['Arabic'],
    currencies: ['Saudi riyal (ر.س)'],
    flag: '🇸🇦',
  ),
  WorldCountryData(
    name: 'Senegal',
    cca2: 'SN',
    cca3: 'SEN',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 14.000000,
    lng: -14.000000,
    capital: 'Dakar',
    languages: ['French'],
    currencies: ['West African CFA franc (Fr)'],
    flag: '🇸🇳',
  ),
  WorldCountryData(
    name: 'Serbia',
    cca2: 'RS',
    cca3: 'SRB',
    region: 'Europe',
    subregion: 'Southeast Europe',
    lat: 44.000000,
    lng: 21.000000,
    capital: 'Belgrade',
    languages: ['Serbian'],
    currencies: ['Serbian dinar (дин.)'],
    flag: '🇷🇸',
  ),
  WorldCountryData(
    name: 'Seychelles',
    cca2: 'SC',
    cca3: 'SYC',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -4.583333,
    lng: 55.666667,
    capital: 'Victoria',
    languages: ['Seychellois Creole', 'English', 'French'],
    currencies: ['Seychellois rupee (₨)'],
    flag: '🇸🇨',
  ),
  WorldCountryData(
    name: 'Sierra Leone',
    cca2: 'SL',
    cca3: 'SLE',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 8.500000,
    lng: -11.500000,
    capital: 'Freetown',
    languages: ['English'],
    currencies: ['Sierra Leonean leone (Le)'],
    flag: '🇸🇱',
  ),
  WorldCountryData(
    name: 'Singapore',
    cca2: 'SG',
    cca3: 'SGP',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: 1.366667,
    lng: 103.800000,
    capital: 'Singapore',
    languages: ['English', 'Malay', 'Tamil', 'Chinese'],
    currencies: ['Singapore dollar (\$)'],
    flag: '🇸🇬',
  ),
  WorldCountryData(
    name: 'Sint Maarten',
    cca2: 'SX',
    cca3: 'SXM',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.033333,
    lng: -63.050000,
    capital: 'Philipsburg',
    languages: ['English', 'French', 'Dutch'],
    currencies: ['Netherlands Antillean guilder (ƒ)'],
    flag: '🇸🇽',
  ),
  WorldCountryData(
    name: 'Slovakia',
    cca2: 'SK',
    cca3: 'SVK',
    region: 'Europe',
    subregion: 'Central Europe',
    lat: 48.666667,
    lng: 19.500000,
    capital: 'Bratislava',
    languages: ['Slovak'],
    currencies: ['Euro (€)'],
    flag: '🇸🇰',
  ),
  WorldCountryData(
    name: 'Slovenia',
    cca2: 'SI',
    cca3: 'SVN',
    region: 'Europe',
    subregion: 'Central Europe',
    lat: 46.116667,
    lng: 14.816667,
    capital: 'Ljubljana',
    languages: ['Slovene'],
    currencies: ['Euro (€)'],
    flag: '🇸🇮',
  ),
  WorldCountryData(
    name: 'Solomon Islands',
    cca2: 'SB',
    cca3: 'SLB',
    region: 'Oceania',
    subregion: 'Melanesia',
    lat: -8.000000,
    lng: 159.000000,
    capital: 'Honiara',
    languages: ['English'],
    currencies: ['Solomon Islands dollar (\$)'],
    flag: '🇸🇧',
  ),
  WorldCountryData(
    name: 'Somalia',
    cca2: 'SO',
    cca3: 'SOM',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: 10.000000,
    lng: 49.000000,
    capital: 'Mogadishu',
    languages: ['Arabic', 'Somali'],
    currencies: ['Somali shilling (Sh)'],
    flag: '🇸🇴',
  ),
  WorldCountryData(
    name: 'South Africa',
    cca2: 'ZA',
    cca3: 'ZAF',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -29.000000,
    lng: 24.000000,
    capital: 'Pretoria',
    languages: [
      'Afrikaans',
      'English',
      'Southern Ndebele',
      'Northern Sotho',
      'Southern Sotho',
      'Swazi',
      'Tswana',
      'Tsonga',
      'Venda',
      'Xhosa',
      'Zulu',
    ],
    currencies: ['South African rand (R)'],
    flag: '🇿🇦',
  ),
  WorldCountryData(
    name: 'South Georgia',
    cca2: 'GS',
    cca3: 'SGS',
    region: 'Antarctic',
    subregion: '',
    lat: -54.500000,
    lng: -37.000000,
    capital: 'King Edward Point',
    languages: ['English'],
    currencies: ['Saint Helena pound (£)'],
    flag: '🇬🇸',
  ),
  WorldCountryData(
    name: 'South Korea',
    cca2: 'KR',
    cca3: 'KOR',
    region: 'Asia',
    subregion: 'Eastern Asia',
    lat: 37.000000,
    lng: 127.500000,
    capital: 'Seoul',
    languages: ['Korean'],
    currencies: ['South Korean won (₩)'],
    flag: '🇰🇷',
  ),
  WorldCountryData(
    name: 'South Sudan',
    cca2: 'SS',
    cca3: 'SSD',
    region: 'Africa',
    subregion: 'Middle Africa',
    lat: 7.000000,
    lng: 30.000000,
    capital: 'Juba',
    languages: ['English'],
    currencies: ['South Sudanese pound (£)'],
    flag: '🇸🇸',
  ),
  WorldCountryData(
    name: 'Spain',
    cca2: 'ES',
    cca3: 'ESP',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 40.000000,
    lng: -4.000000,
    capital: 'Madrid',
    languages: ['Spanish'],
    currencies: ['Euro (€)'],
    flag: '🇪🇸',
  ),
  WorldCountryData(
    name: 'Sri Lanka',
    cca2: 'LK',
    cca3: 'LKA',
    region: 'Asia',
    subregion: 'Southern Asia',
    lat: 7.000000,
    lng: 81.000000,
    capital: 'Colombo',
    languages: ['Sinhala', 'Tamil'],
    currencies: ['Sri Lankan rupee (Rs  රු)'],
    flag: '🇱🇰',
  ),
  WorldCountryData(
    name: 'Sudan',
    cca2: 'SD',
    cca3: 'SDN',
    region: 'Africa',
    subregion: 'Northern Africa',
    lat: 15.000000,
    lng: 30.000000,
    capital: 'Khartoum',
    languages: ['Arabic', 'English'],
    currencies: ['Sudanese pound (PT)'],
    flag: '🇸🇩',
  ),
  WorldCountryData(
    name: 'Suriname',
    cca2: 'SR',
    cca3: 'SUR',
    region: 'Americas',
    subregion: 'South America',
    lat: 4.000000,
    lng: -56.000000,
    capital: 'Paramaribo',
    languages: ['Dutch'],
    currencies: ['Surinamese dollar (\$)'],
    flag: '🇸🇷',
  ),
  WorldCountryData(
    name: 'Svalbard and Jan Mayen',
    cca2: 'SJ',
    cca3: 'SJM',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 78.000000,
    lng: 20.000000,
    capital: 'Longyearbyen',
    languages: ['Norwegian'],
    currencies: ['krone (kr)'],
    flag: '🇸🇯',
  ),
  WorldCountryData(
    name: 'Sweden',
    cca2: 'SE',
    cca3: 'SWE',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 62.000000,
    lng: 15.000000,
    capital: 'Stockholm',
    languages: ['Swedish'],
    currencies: ['Swedish krona (kr)'],
    flag: '🇸🇪',
  ),
  WorldCountryData(
    name: 'Switzerland',
    cca2: 'CH',
    cca3: 'CHE',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 47.000000,
    lng: 8.000000,
    capital: 'Bern',
    languages: ['French', 'Swiss German', 'Italian', 'Romansh'],
    currencies: ['Swiss franc (Fr.)'],
    flag: '🇨🇭',
  ),
  WorldCountryData(
    name: 'Syria',
    cca2: 'SY',
    cca3: 'SYR',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 35.000000,
    lng: 38.000000,
    capital: 'Damascus',
    languages: ['Arabic'],
    currencies: ['Syrian pound (£)'],
    flag: '🇸🇾',
  ),
  WorldCountryData(
    name: 'Taiwan',
    cca2: 'TW',
    cca3: 'TWN',
    region: 'Asia',
    subregion: 'Eastern Asia',
    lat: 23.500000,
    lng: 121.000000,
    capital: 'Taipei',
    languages: ['Chinese'],
    currencies: ['New Taiwan dollar (\$)'],
    flag: '🇹🇼',
  ),
  WorldCountryData(
    name: 'Tajikistan',
    cca2: 'TJ',
    cca3: 'TJK',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 39.000000,
    lng: 71.000000,
    capital: 'Dushanbe',
    languages: ['Russian', 'Tajik'],
    currencies: ['Tajikistani somoni (ЅМ)'],
    flag: '🇹🇯',
  ),
  WorldCountryData(
    name: 'Tanzania',
    cca2: 'TZ',
    cca3: 'TZA',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -6.000000,
    lng: 35.000000,
    capital: 'Dodoma',
    languages: ['English', 'Swahili'],
    currencies: ['Tanzanian shilling (Sh)'],
    flag: '🇹🇿',
  ),
  WorldCountryData(
    name: 'Thailand',
    cca2: 'TH',
    cca3: 'THA',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: 15.000000,
    lng: 100.000000,
    capital: 'Bangkok',
    languages: ['Thai'],
    currencies: ['Thai baht (฿)'],
    flag: '🇹🇭',
  ),
  WorldCountryData(
    name: 'Timor-Leste',
    cca2: 'TL',
    cca3: 'TLS',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: -8.833333,
    lng: 125.916667,
    capital: 'Dili',
    languages: ['Portuguese', 'Tetum'],
    currencies: ['United States dollar (\$)'],
    flag: '🇹🇱',
  ),
  WorldCountryData(
    name: 'Togo',
    cca2: 'TG',
    cca3: 'TGO',
    region: 'Africa',
    subregion: 'Western Africa',
    lat: 8.000000,
    lng: 1.166667,
    capital: 'Lomé',
    languages: ['French'],
    currencies: ['West African CFA franc (Fr)'],
    flag: '🇹🇬',
  ),
  WorldCountryData(
    name: 'Tokelau',
    cca2: 'TK',
    cca3: 'TKL',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -9.000000,
    lng: -172.000000,
    capital: 'Fakaofo',
    languages: ['English', 'Samoan', 'Tokelauan'],
    currencies: ['New Zealand dollar (\$)'],
    flag: '🇹🇰',
  ),
  WorldCountryData(
    name: 'Tonga',
    cca2: 'TO',
    cca3: 'TON',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -20.000000,
    lng: -175.000000,
    capital: 'Nuku\'alofa',
    languages: ['English', 'Tongan'],
    currencies: ['Tongan paʻanga (T\$)'],
    flag: '🇹🇴',
  ),
  WorldCountryData(
    name: 'Trinidad and Tobago',
    cca2: 'TT',
    cca3: 'TTO',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 11.000000,
    lng: -61.000000,
    capital: 'Port of Spain',
    languages: ['English'],
    currencies: ['Trinidad and Tobago dollar (\$)'],
    flag: '🇹🇹',
  ),
  WorldCountryData(
    name: 'Tunisia',
    cca2: 'TN',
    cca3: 'TUN',
    region: 'Africa',
    subregion: 'Northern Africa',
    lat: 34.000000,
    lng: 9.000000,
    capital: 'Tunis',
    languages: ['Arabic'],
    currencies: ['Tunisian dinar (د.ت)'],
    flag: '🇹🇳',
  ),
  WorldCountryData(
    name: 'Türkiye',
    cca2: 'TR',
    cca3: 'TUR',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 39.000000,
    lng: 35.000000,
    capital: 'Ankara',
    languages: ['Turkish'],
    currencies: ['Turkish lira (₺)'],
    flag: '🇹🇷',
  ),
  WorldCountryData(
    name: 'Turkmenistan',
    cca2: 'TM',
    cca3: 'TKM',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 40.000000,
    lng: 60.000000,
    capital: 'Ashgabat',
    languages: ['Russian', 'Turkmen'],
    currencies: ['Turkmenistan manat (m)'],
    flag: '🇹🇲',
  ),
  WorldCountryData(
    name: 'Turks and Caicos Islands',
    cca2: 'TC',
    cca3: 'TCA',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 21.750000,
    lng: -71.583333,
    capital: 'Cockburn Town',
    languages: ['English'],
    currencies: ['United States dollar (\$)'],
    flag: '🇹🇨',
  ),
  WorldCountryData(
    name: 'Tuvalu',
    cca2: 'TV',
    cca3: 'TUV',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -8.000000,
    lng: 178.000000,
    capital: 'Funafuti',
    languages: ['English', 'Tuvaluan'],
    currencies: ['Australian dollar (\$)', 'Tuvaluan dollar (\$)'],
    flag: '🇹🇻',
  ),
  WorldCountryData(
    name: 'Uganda',
    cca2: 'UG',
    cca3: 'UGA',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: 1.000000,
    lng: 32.000000,
    capital: 'Kampala',
    languages: ['English', 'Swahili'],
    currencies: ['Ugandan shilling (Sh)'],
    flag: '🇺🇬',
  ),
  WorldCountryData(
    name: 'Ukraine',
    cca2: 'UA',
    cca3: 'UKR',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 49.000000,
    lng: 32.000000,
    capital: 'Kyiv',
    languages: ['Ukrainian'],
    currencies: ['Ukrainian hryvnia (₴)'],
    flag: '🇺🇦',
  ),
  WorldCountryData(
    name: 'United Arab Emirates',
    cca2: 'AE',
    cca3: 'ARE',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 24.000000,
    lng: 54.000000,
    capital: 'Abu Dhabi',
    languages: ['Arabic'],
    currencies: ['United Arab Emirates dirham (د.إ)'],
    flag: '🇦🇪',
  ),
  WorldCountryData(
    name: 'United Kingdom',
    cca2: 'GB',
    cca3: 'GBR',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 54.000000,
    lng: -2.000000,
    capital: 'London',
    languages: ['English'],
    currencies: ['British pound (£)'],
    flag: '🇬🇧',
  ),
  WorldCountryData(
    name: 'United States',
    cca2: 'US',
    cca3: 'USA',
    region: 'Americas',
    subregion: 'North America',
    lat: 38.000000,
    lng: -97.000000,
    capital: 'Washington D.C.',
    languages: ['English'],
    currencies: ['United States dollar (\$)'],
    flag: '🇺🇸',
  ),
  WorldCountryData(
    name: 'United States Minor Outlying Islands',
    cca2: 'UM',
    cca3: 'UMI',
    region: 'Americas',
    subregion: 'North America',
    lat: 19.300000,
    lng: 166.633333,
    capital: null,
    languages: ['English'],
    currencies: ['United States dollar (\$)'],
    flag: '🇺🇲',
  ),
  WorldCountryData(
    name: 'United States Virgin Islands',
    cca2: 'VI',
    cca3: 'VIR',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.350000,
    lng: -64.933333,
    capital: 'Charlotte Amalie',
    languages: ['English'],
    currencies: ['United States dollar (\$)'],
    flag: '🇻🇮',
  ),
  WorldCountryData(
    name: 'Uruguay',
    cca2: 'UY',
    cca3: 'URY',
    region: 'Americas',
    subregion: 'South America',
    lat: -33.000000,
    lng: -56.000000,
    capital: 'Montevideo',
    languages: ['Spanish'],
    currencies: ['Uruguayan peso (\$)'],
    flag: '🇺🇾',
  ),
  WorldCountryData(
    name: 'Uzbekistan',
    cca2: 'UZ',
    cca3: 'UZB',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 41.000000,
    lng: 64.000000,
    capital: 'Tashkent',
    languages: ['Russian', 'Uzbek'],
    currencies: ['Uzbekistani soʻm (so\'m)'],
    flag: '🇺🇿',
  ),
  WorldCountryData(
    name: 'Vanuatu',
    cca2: 'VU',
    cca3: 'VUT',
    region: 'Oceania',
    subregion: 'Melanesia',
    lat: -16.000000,
    lng: 167.000000,
    capital: 'Port Vila',
    languages: ['Bislama', 'English', 'French'],
    currencies: ['Vanuatu vatu (Vt)'],
    flag: '🇻🇺',
  ),
  WorldCountryData(
    name: 'Vatican City',
    cca2: 'VA',
    cca3: 'VAT',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 41.900000,
    lng: 12.450000,
    capital: 'Vatican City',
    languages: ['Italian', 'Latin'],
    currencies: ['Euro (€)'],
    flag: '🇻🇦',
  ),
  WorldCountryData(
    name: 'Venezuela',
    cca2: 'VE',
    cca3: 'VEN',
    region: 'Americas',
    subregion: 'South America',
    lat: 8.000000,
    lng: -66.000000,
    capital: 'Caracas',
    languages: ['Spanish'],
    currencies: ['Venezuelan bolívar soberano (Bs.S.)'],
    flag: '🇻🇪',
  ),
  WorldCountryData(
    name: 'Vietnam',
    cca2: 'VN',
    cca3: 'VNM',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    lat: 16.166667,
    lng: 107.833333,
    capital: 'Hanoi',
    languages: ['Vietnamese'],
    currencies: ['Vietnamese đồng (₫)'],
    flag: '🇻🇳',
  ),
  WorldCountryData(
    name: 'Wallis and Futuna',
    cca2: 'WF',
    cca3: 'WLF',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -13.300000,
    lng: -176.200000,
    capital: 'Mata-Utu',
    languages: ['French'],
    currencies: ['CFP franc (₣)'],
    flag: '🇼🇫',
  ),
  WorldCountryData(
    name: 'Western Sahara',
    cca2: 'EH',
    cca3: 'ESH',
    region: 'Africa',
    subregion: 'Northern Africa',
    lat: 24.500000,
    lng: -13.000000,
    capital: 'El Aaiún',
    languages: ['Berber', 'Hassaniya', 'Spanish'],
    currencies: [
      'Algerian dinar (دج)',
      'Moroccan dirham (DH)',
      'Mauritanian ouguiya (UM)',
    ],
    flag: '🇪🇭',
  ),
  WorldCountryData(
    name: 'Yemen',
    cca2: 'YE',
    cca3: 'YEM',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 15.000000,
    lng: 48.000000,
    capital: 'Sana\'a',
    languages: ['Arabic'],
    currencies: ['Yemeni rial (﷼)'],
    flag: '🇾🇪',
  ),
  WorldCountryData(
    name: 'Zambia',
    cca2: 'ZM',
    cca3: 'ZMB',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -15.000000,
    lng: 30.000000,
    capital: 'Lusaka',
    languages: ['English'],
    currencies: ['Zambian kwacha (ZK)'],
    flag: '🇿🇲',
  ),
  WorldCountryData(
    name: 'Zimbabwe',
    cca2: 'ZW',
    cca3: 'ZWE',
    region: 'Africa',
    subregion: 'Eastern Africa',
    lat: -20.000000,
    lng: 30.000000,
    capital: 'Harare',
    languages: [
      'Chibarwe',
      'English',
      'Kalanga',
      'Khoisan',
      'Ndau',
      'Northern Ndebele',
      'Chewa',
      'Shona',
      'Sotho',
      'Tonga',
      'Tswana',
      'Tsonga',
      'Venda',
      'Xhosa',
      'Zimbabwean Sign Language',
    ],
    currencies: [
      'Botswana pula (P)',
      'Chinese yuan (¥)',
      'Euro (€)',
      'British pound (£)',
      'Indian rupee (₹)',
      'Japanese yen (¥)',
      'United States dollar (\$)',
      'South African rand (Rs)',
      'Zimbabwean bonds (\$)',
    ],
    flag: '🇿🇼',
  ),
];
